project:
  type: website
  output-dir: docs

website:
  title: "Mireyas1032.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
          - href: Assignment 1.qmd
            text: Assignment 1
          - href: Assignment 2.qmd
            text: Assignemnt 2
          - href: Assignment 3.qmd
            text: Assignment 3


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

